---
title: "Datafest18"
author: "Sicong Li"
date: "March 23, 2018"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(readr)
```

```{r}
Indeedsample <- read_csv('/Users/caroline/Downloads/Indeed_mini.csv')
Indeedsample <- Indeedsample %>%
  filter(country == "US") %>%
  select(country, admin1, city, employerIndustry, applies, employerJobCount, candStatusReviewedCount, jobagedays, date)

Visadata <- read_csv('/Users/caroline/Downloads/H-1B_Disclosure_Data_FY17.csv')
Visa_sample <- sample_n(Visadata, 100000)
```

```{r}
IndeedData <- Indeedsample %>%
  filter(country == "US") %>%
  select(country, admin1, city, employerIndustry, applies, employerJobCount, candStatusReviewedCount, jobagedays, date) %>%
  mutate(LaborSupplyDemRatio = applies/ employerJobCount) %>%
  group_by(date, employerIndustry) %>%
  summarise(mean = mean(LaborSupplyDemRatio))

Indeedplot <- ggplot(data=IndeedData, aes(x=date, y=mean, color=employerIndustry)) +
  geom_line()
Indeedplot
```

```{r}
Indeeddate <- data.frame( date = Indeedsample$date,
                 year = as.numeric(format(Indeedsample$date, format = "%Y")),
                 month = as.numeric(format(Indeedsample$date, format = "%m")))
Indeedbymonth <- Indeedsample %>%
  full_join(Indeeddate, by = "date") %>%
  unite(year_month,year,month)  %>%
  filter(country == "US") %>%
  select(country, admin1, city, employerIndustry, applies, employerJobCount, candStatusReviewedCount, jobagedays, year_month) %>%
  mutate(LaborSupplyDemRatio = applies/ employerJobCount) %>%
  group_by(year_month, employerIndustry) %>%
  summarise(mean = mean(LaborSupplyDemRatio))

Indeedplot <- ggplot(data=Indeedbymonth, aes(x=year_month, y=mean, color=employerIndustry, group = employerIndustry)) +
  geom_line()
Indeedplot
```


```{r}
IndeedTop5 <- Indeedsample %>%
  mutate(LaborSupplyDemRatio = applies/ employerJobCount) %>%
  group_by(employerIndustry) %>%
  summarise(sum = sum(LaborSupplyDemRatio)) %>%
  arrange(sum) %>%
  head(5)
```

